### ISSUE TITLE
能将NPMultiStretchImage类放出来吗？

### ISSUE THREAD

**Issue by zgjff** [zxinsunshine/NinePatchKit#1]
我需要加载网络的.9文件,需要自己处理逻辑

**Comment by zxinsunshine** [comment]
NPMultiStretchImage用于缓存一些.9的处理数据，为绘制提供数据支持，只有NinePathImageView内部才用的到，封装的是.9的绘制规则，所以没有开出来。
网络加载网络.9文件，先down下来，然后调用-[NinePatchUtils imageWithContentsOfFile:]就能实现了

**Comment by zgjff** [comment]
那NinePatchUtils再添加一个方法imageWithData也行

**Comment by zxinsunshine** [comment]
可以，我加上了，你更新pods版本就行
