### ISSUE TITLE
能不能再额外添加个方法

### ISSUE THREAD

**Issue by zgjff** [zxinsunshine/NinePatchKit#2]
因为.9图是url,在使用`SDWebImageManager.shared.loadImage`下载图片的时候,如果已经存在Image了,是获取不到Data的；
所以能不能那个再加个方法: `+ (ImageClass *)imageWithImage:(UIImage *)image;`

**Comment by zxinsunshine** [comment]
> 因为.9图是url,在使用`SDWebImageManager.shared.loadImage`下载图片的时候,如果已经存在Image了,是获取不到Data的；
> 所以能不能那个再加个方法: `+ (ImageClass *)imageWithImage:(UIImage *)image;`

NSData *data = UIImagePNGRepresentation(image); 转一下就行，我这边处理的话也是走这个逻辑

**Comment by zgjff** [comment]
```swift
func loadNinePatchImage(_ url: URL, completion: @escaping (Result<(image: UIImage, padding: UIEdgeInsets, url: URL), LoadImageError>) -> ()) {
        let ckey = SDWebImageManager.shared.cacheKey(for: url)! as NSString
        if let img = cache.object(forKey: ckey) {
            let padding = NinePatchUtils.padding(for: img)
            completion(.success((img, padding, url)))
            return
        }
        SDWebImageManager.shared.loadImage(with: url, options: [], context: nil, progress: nil) { img, data, _, _, _, u in
            guard let ul = u else {
                DispatchQueue.main.async {
                    completion(.failure(.none))
                }
                return
            }
            if let img = img, let data = img.pngData() {
                let ukey = SDWebImageManager.shared.cacheKey(for: ul)! as NSString
                let img = NinePatchUtils.image(with: data)
                let padding = NinePatchUtils.padding(for: img)
                self.cache.setObject(img, forKey: ukey)
                DispatchQueue.main.async {
                    completion(.success((img, padding, ul)))
                }
                return
            }
            guard let d = data else {
                DispatchQueue.main.async {
                    completion(.failure(.none))
                }
                return
            }
            let ukey = SDWebImageManager.shared.cacheKey(for: ul)! as NSString
            let img = NinePatchUtils.image(with: d)
            let padding = NinePatchUtils.padding(for: img)
            self.cache.setObject(img, forKey: ukey)
            DispatchQueue.main.async {
                completion(.success((img, padding, ul)))
            }
        }
    }
```
使用pngData()这个逻辑的话,会造成变形。。。。。。

**Comment by zxinsunshine** [comment]
> ```swift
> func loadNinePatchImage(_ url: URL, completion: @escaping (Result<(image: UIImage, padding: UIEdgeInsets, url: URL), LoadImageError>) -> ()) {
>         let ckey = SDWebImageManager.shared.cacheKey(for: url)! as NSString
>         if let img = cache.object(forKey: ckey) {
>             let padding = NinePatchUtils.padding(for: img)
>             completion(.success((img, padding, url)))
>             return
>         }
>         SDWebImageManager.shared.loadImage(with: url, options: [], context: nil, progress: nil) { img, data, _, _, _, u in
>             guard let ul = u else {
>                 DispatchQueue.main.async {
>                     completion(.failure(.none))
>                 }
>                 return
>             }
>             if let img = img, let data = img.pngData() {
>                 let ukey = SDWebImageManager.shared.cacheKey(for: ul)! as NSString
>                 let img = NinePatchUtils.image(with: data)
>                 let padding = NinePatchUtils.padding(for: img)
>                 self.cache.setObject(img, forKey: ukey)
>                 DispatchQueue.main.async {
>                     completion(.success((img, padding, ul)))
>                 }
>                 return
>             }
>             guard let d = data else {
>                 DispatchQueue.main.async {
>                     completion(.failure(.none))
>                 }
>                 return
>             }
>             let ukey = SDWebImageManager.shared.cacheKey(for: ul)! as NSString
>             let img = NinePatchUtils.image(with: d)
>             let padding = NinePatchUtils.padding(for: img)
>             self.cache.setObject(img, forKey: ukey)
>             DispatchQueue.main.async {
>                 completion(.success((img, padding, ul)))
>             }
>         }
>     }
> ```
> 
> 使用pngData()这个逻辑的话,会造成变形。。。。。。

不好意思，上一个回答有误，点九图解析，必须是对原文件的二进制数据解析。
当先通过系统API读取文件解码成UIImage对象时，会抹掉其中的点九图相关数据，所以此时获取UIImage对象的pngData数据后，经过NinePatchKit解析出的只是普通的图片对象，所以渲染的时候是普通放缩，也就是你遇到的变形现象。
SD的loadImage除了返回解码后的UIImage对象，也会返回原data对象，通过原data对象就能正常解析了，如：
```
SDWebImageManager.shared.loadImage(with: url, options: [], progress: nil) { img, data, error, _, _, _ in
          if let downloadData = data {
              let showImage = NinePatchUtils.image(with: downloadData)
              let padding = NinePatchUtils.padding(for: showImage)
              print(padding)
              print(showImage)
              // more logic ...
          }
      }
```
